CREATE TABLE IF NOT EXISTS projects (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '项目ID',
  name VARCHAR(200) NOT NULL COMMENT '项目名称',
  summary TEXT COMMENT '项目简介',
  cover_url VARCHAR(500) COMMENT '封面图URL',
  video_url VARCHAR(500) COMMENT '演示视频URL',
  content_html MEDIUMTEXT COMMENT '项目详情HTML内容',
  external_url VARCHAR(500) COMMENT '外部链接',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序权重(数字大在前)',
  is_public TINYINT NOT NULL DEFAULT 1 COMMENT '是否公开(1:公开 0:隐藏)',
  view_count INT NOT NULL DEFAULT 0 COMMENT '浏览次数',
  tags VARCHAR(255) COMMENT '标签',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目表';

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '留言ID',
  nickname VARCHAR(100) NOT NULL COMMENT '昵称',
  contact VARCHAR(200) COMMENT '联系方式',
  content TEXT NOT NULL COMMENT '留言内容',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0:未处理 1:已处理)',
  ip VARCHAR(64) COMMENT 'IP地址',
  ua VARCHAR(255) COMMENT 'User-Agent',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  INDEX idx_messages_status (status),
  INDEX idx_messages_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='留言表';

CREATE TABLE IF NOT EXISTS replies (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '回复ID',
  message_id BIGINT NOT NULL COMMENT '关联的留言ID',
  content TEXT NOT NULL COMMENT '回复内容',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  INDEX idx_replies_message (message_id),
  CONSTRAINT fk_replies_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='留言回复表';

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '管理员ID',
  username VARCHAR(100) NOT NULL UNIQUE COMMENT '用户名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希值',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员表';